import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Avatar, AvatarImage, AvatarFallback } from "@radix-ui/react-avatar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-16 px-6 py-2 flex justify-between border-b border-gray-200">
          <Image
            src="/logo.png"
            alt=""
            width={500}
            height={500}
            className="h-full w-auto aspect-square"
          />
          <Avatar>
            <AvatarImage
              src="https://github.com/shadcn.png"
              alt="プロフィール画像"
              className="h-full w-auto aspect-square rounded-full"
            />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
        </div>
        {children}
      </body>
    </html>
  );
}
